version: '3.7'

services:
  db:
    container_name: postgres-adminchik
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
    - 5433:5432
    volumes:
    - postgres_data:/var/lib/postgresql/data
    networks:
    - adminchik
  redis:
    container_name: redis-adminchik
    image: redis:6.0
    restart: always
    ports:
    - 6379:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
    - redis_data:/data
    networks:
    - adminchik
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - adminchik

volumes: 
  postgres_data:
  redis_data:
  minio_data:

networks:
  adminchik: