version: '3.7'

services:
  db:
    container_name: postgres-adminchik
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
    - 5433:5432
    volumes:
    - postgres_data:/var/lib/postgresql/data
    networks:
    - adminchik
  redis:
    container_name: redis-adminchik
    image: redis:6.0
    restart: always
    ports:
    - 6379:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
    - redis_data:/data
    networks:
    - adminchik
  minio:
    container_name: minio-adminchik
    image: minio/minio:RELEASE.2020-08-08T04-50-06Z
    restart: always
    volumes:
    - minio_data:/data
    ports:
    - 9000:9000
    networks:
    - adminchik
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3

volumes: 
  postgres_data:
  redis_data:
  minio_data:

networks:
  adminchik: