version: '3.7'

services:
  db:
    container_name: postgres-adminchik
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
    - 5433:5432
    volumes:
    - postgres_data:/var/lib/postgresql/data
    networks:
    - adminchik
  redis:
    container_name: redis-adminchik
    image: redis:6.0
    restart: always
    ports:
    - 6379:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
    - redis_data:/data
    networks:
    - adminchik
  minio:
    image: minio/minio
    container_name: minio-adminchik
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - adminchik
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-adminchik
    ports:
      - "8123:8123"
      - "9003:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    networks:
      - adminchik
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DB:-default}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-default}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-password}

volumes: 
  postgres_data:
  redis_data:
  minio_data:
  clickhouse_data:

networks:
  adminchik: